### ISSUE TITLE
 ML model alerts with aml_training_dataset.csv

### ISSUE THREAD

**Issue by zolotoy** [awslabs/machine-learning-samples#10]
Hello!

I am trying to classify @awscloud tweets with ML model based on aml_training_dataset.csv
Went through all the steps in tutorial, but none of the tweets was matched.

I didn't understand what I did wrong. Maybe problem is with ML model alerts? (see image below)

<img width="669" alt="alerts" src="https://cloud.githubusercontent.com/assets/25311/10718046/fcd3b708-7b71-11e5-8596-b3a90261af6e.png">

**Comment by timtianmingzheng** [comment]
Could you click into the detailed page of the evaluation datasource, and check what entity status it is and how the data statistics looks like over there?

**Comment by zolotoy** [comment]
@timtianmingzheng

<img width="852" alt="2015-10-26 13 18 55" src="https://cloud.githubusercontent.com/assets/25311/10727653/272accea-7be4-11e5-968e-19098d8c78ff.png">

**Comment by timtianmingzheng** [comment]
Looks to me that the evaluation datasource does not come with computed data statistics, and therefore the alerts is not working. Anyway, I don't think the alert here indicates any useful clue for your issue.

Could you please tell me more about how did you find out: "none of the tweets was matched"? What tweets are you trying to match with? At which step of [these five](https://github.com/awslabs/machine-learning-samples/tree/master/social-media) you are stuck?

**Comment by zolotoy** [comment]
I stuck at Step 5b and Step 5c.

Step 5b: ML model didn't match any tweet from `line_separated_tweets_json.txt` what I gather from @awscloud

Step 5c: I didn't receive any notification from SNS about Actionable tweets.

I found another alert with datasource. Maybe it affects tweets processing?
<img width="1041" alt="quality" src="https://cloud.githubusercontent.com/assets/25311/10757278/8a381ee0-7cb2-11e5-928d-fa6136a04a39.png">

**Comment by zolotoy** [comment]
Seems like I fix my problem. It was issue with policies at tweetStreamExecutionRole.
Thanks @timtianmingzheng.

**Comment by timtianmingzheng** [comment]
Glad that you are unblocked now. Please feel free to leave feedback/comment and help us improve the sample app. Thanks!
